/**
 * Extra-payment email — sent by the admin "Modifică" flow when an order
 * needs more money than was originally captured (add-on added, urgency
 * upgraded, courier swapped to a more expensive option). The customer
 * receives a Stripe Elements link tied to the PaymentIntent we just
 * created on their behalf.
 *
 * Both HTML and plain-text emitted; HTML is fully inline (no external
 * assets) so it renders in email clients that block images.
 */

export interface ExtraPaymentEmailInput {
  customerFirstName?: string | null;
  orderNumber: string;
  /** Amount the customer needs to pay (RON). */
  amountRon: number;
  /** What was changed/added — surfaces in body so customer knows what
   *  they're paying for. Generated by `describeChanges` upstream. */
  changesDescription: string;
  /** URL the customer clicks to complete the payment. We expose the
   *  PaymentIntent `client_secret` via a tenant URL that the frontend
   *  resolves to a Stripe Elements page. */
  paymentUrl: string;
}

export function buildExtraPaymentSubject(input: ExtraPaymentEmailInput): string {
  return `Modificare comandă ${input.orderNumber} — plată suplimentară ${input.amountRon.toFixed(2)} RON`;
}

export function buildExtraPaymentHtml(input: ExtraPaymentEmailInput): string {
  const greeting = input.customerFirstName
    ? `Salut ${escapeHtml(input.customerFirstName)},`
    : 'Salut,';
  return `<!doctype html>
<html lang="ro">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>${escapeHtml(buildExtraPaymentSubject(input))}</title>
  </head>
  <body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;color:#1f2937">
    <div style="max-width:560px;margin:0 auto;padding:24px">
      <div style="background:#ffffff;border:1px solid #e5e7eb;border-radius:12px;padding:32px 28px">
        <p style="margin:0 0 12px 0;font-size:14px;color:#6b7280">Comanda ${escapeHtml(input.orderNumber)}</p>
        <h1 style="margin:0 0 16px 0;font-size:22px;line-height:1.3;color:#111827">${greeting}</h1>
        <p style="margin:0 0 16px 0;font-size:15px;line-height:1.6">
          Am modificat comanda ta conform discuției. Pentru a finaliza, este nevoie de o plată suplimentară.
        </p>
        <div style="background:#fffbeb;border:2px solid #fcd34d;border-radius:10px;padding:18px;margin:0 0 20px 0">
          <p style="margin:0 0 6px 0;font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#92400e">Sumă de plată</p>
          <p style="margin:0;font-size:32px;font-weight:bold;color:#78350f;tabular-nums">${input.amountRon.toFixed(2)} RON</p>
          <p style="margin:8px 0 0 0;font-size:13px;color:#92400e">${escapeHtml(input.changesDescription)}</p>
        </div>
        <p style="margin:0 0 24px 0;font-size:14px;color:#6b7280;line-height:1.6">
          Plata se face în siguranță prin Stripe. Datele tale de card sunt criptate end-to-end și nu sunt stocate de noi.
        </p>
        <p style="margin:0 0 8px 0;text-align:center">
          <a href="${escapeAttr(input.paymentUrl)}" style="display:inline-block;padding:14px 32px;background:#ecb95f;color:#1f2937;font-weight:600;text-decoration:none;border-radius:10px;font-size:15px">
            Plătește ${input.amountRon.toFixed(2)} RON →
          </a>
        </p>
        <p style="margin:14px 0 0 0;text-align:center;font-size:12px;color:#9ca3af">
          Link-ul rămâne valid 24h. Dacă apare orice problemă, răspunde la acest email.
        </p>
      </div>
      <p style="margin:18px 0 0 0;text-align:center;font-size:12px;color:#9ca3af;line-height:1.5">
        Ai primit acest email pentru că ai o comandă activă pe eGhișeul.ro. Modificarea + plata sunt înregistrate în istoricul comenzii.
      </p>
    </div>
  </body>
</html>`;
}

export function buildExtraPaymentText(input: ExtraPaymentEmailInput): string {
  const greeting = input.customerFirstName
    ? `Salut ${input.customerFirstName},`
    : 'Salut,';
  return [
    `Comanda ${input.orderNumber}`,
    '',
    greeting,
    '',
    `Am modificat comanda ta conform discuției. Pentru a finaliza, este nevoie de o plată suplimentară de ${input.amountRon.toFixed(2)} RON.`,
    '',
    `Modificări: ${input.changesDescription}`,
    '',
    `Plătește în siguranță prin Stripe: ${input.paymentUrl}`,
    '',
    'Link-ul rămâne valid 24h. Dacă apare orice problemă, răspunde la acest email.',
    '',
    '— Echipa eGhișeul.ro',
  ].join('\n');
}

// ─── small html escape, no template engine needed ────────────────────────────

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}
