/**
 * Extra-payment email — sent by the admin "Modifică" flow when an order
 * needs more money than was originally captured (add-on added, urgency
 * upgraded, courier swapped to a more expensive option). The customer
 * receives a Stripe Elements link tied to the PaymentIntent we just
 * created on their behalf.
 *
 * Both HTML and plain-text emitted; wrapped in the shared branded shell
 * so it matches every other customer email.
 */
import { brandedEmailHtml, ctaButton } from './branded-layout';

export interface ExtraPaymentEmailInput {
  customerFirstName?: string | null;
  orderNumber: string;
  /** Amount the customer needs to pay (RON). */
  amountRon: number;
  /** What was changed/added — surfaces in body so customer knows what
   *  they're paying for. Generated by `describeChanges` upstream. */
  changesDescription: string;
  /** URL the customer clicks to complete the payment. We expose the
   *  PaymentIntent `client_secret` via a tenant URL that the frontend
   *  resolves to a Stripe Elements page. */
  paymentUrl: string;
}

export function buildExtraPaymentSubject(input: ExtraPaymentEmailInput): string {
  return `Modificare comandă ${input.orderNumber} — plată suplimentară ${input.amountRon.toFixed(2)} RON`;
}

export function buildExtraPaymentHtml(input: ExtraPaymentEmailInput): string {
  const greeting = input.customerFirstName
    ? `Salut ${escapeHtml(input.customerFirstName)},`
    : 'Salut,';
  return brandedEmailHtml({
    preheader: `Plată suplimentară ${input.amountRon.toFixed(2)} RON pentru comanda ${input.orderNumber}`,
    content: `
        <p style="margin:0 0 10px;font-size:13px;color:#64748b;">Comanda <span style="font-family:monospace;font-weight:700;color:#0f172a;">${escapeHtml(input.orderNumber)}</span></p>
        <h1 style="margin:0 0 12px;color:#0B1B33;font-size:20px;">${greeting}</h1>
        <p style="margin:0 0 16px;color:#475569;font-size:14px;line-height:1.6;">Am modificat comanda ta conform discuției. Pentru a finaliza, este nevoie de o plată suplimentară.</p>
        <div style="background:#fffbeb;border:2px solid #fcd34d;border-radius:10px;padding:18px;margin:0 0 20px;">
          <p style="margin:0 0 6px;font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#92400e;">Sumă de plată</p>
          <p style="margin:0;font-size:32px;font-weight:bold;color:#78350f;">${input.amountRon.toFixed(2)} RON</p>
          <p style="margin:8px 0 0;font-size:13px;color:#92400e;">${escapeHtml(input.changesDescription)}</p>
        </div>
        <p style="margin:0 0 6px;font-size:13px;color:#64748b;line-height:1.6;">Plata se face în siguranță prin Stripe. Datele cardului sunt criptate end-to-end și nu sunt stocate de noi.</p>
        ${ctaButton(`Plătește ${input.amountRon.toFixed(2)} RON`, input.paymentUrl)}
        <p style="margin:14px 0 0;text-align:center;font-size:12px;color:#9ca3af;">Link-ul rămâne valid 24h. Orice problemă — răspunde la acest email.</p>`,
  });
}

export function buildExtraPaymentText(input: ExtraPaymentEmailInput): string {
  const greeting = input.customerFirstName
    ? `Salut ${input.customerFirstName},`
    : 'Salut,';
  return [
    `Comanda ${input.orderNumber}`,
    '',
    greeting,
    '',
    `Am modificat comanda ta conform discuției. Pentru a finaliza, este nevoie de o plată suplimentară de ${input.amountRon.toFixed(2)} RON.`,
    '',
    `Modificări: ${input.changesDescription}`,
    '',
    `Plătește în siguranță prin Stripe: ${input.paymentUrl}`,
    '',
    'Link-ul rămâne valid 24h. Dacă apare orice problemă, răspunde la acest email.',
    '',
    '— Echipa eGhișeul.ro',
  ].join('\n');
}

// ─── small html escape, no template engine needed ────────────────────────────

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

