/**
 * robots.txt — generated by Next.js Metadata API.
 *
 * Policy (per SEO master plan 2026-05-20):
 * - Allow standard crawlers everywhere except private routes
 * - Allow AI crawlers (GPTBot, ClaudeBot, PerplexityBot, OAI-SearchBot,
 *   Google-Extended) — modern E-E-A-T signal + visibility in AI Overviews,
 *   ChatGPT search, Perplexity, etc. (~15-25% of discovery traffic by 2026)
 * - Block:
 *   - /admin/   (admin panel, not for indexing)
 *   - /api/     (API routes, no human-readable content)
 *   - /comanda/ (order wizard — user-state, not public content)
 *   - /auth/    (login/register flows)
 *   - /account/ (customer account area)
 */

import type { MetadataRoute } from 'next';
import { BASE_URL } from '@/lib/seo/constants';

const DISALLOW_PATHS = [
  '/admin/',
  '/api/',
  '/comanda/',
  '/auth/',
  '/account/',
  '/orders/',
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // Default policy for all crawlers
      { userAgent: '*', allow: '/', disallow: DISALLOW_PATHS },
      // Explicitly allow major AI crawlers (some default to denied without an entry)
      { userAgent: 'GPTBot', allow: '/', disallow: DISALLOW_PATHS },
      { userAgent: 'OAI-SearchBot', allow: '/', disallow: DISALLOW_PATHS },
      { userAgent: 'ChatGPT-User', allow: '/', disallow: DISALLOW_PATHS },
      { userAgent: 'ClaudeBot', allow: '/', disallow: DISALLOW_PATHS },
      { userAgent: 'Claude-Web', allow: '/', disallow: DISALLOW_PATHS },
      { userAgent: 'PerplexityBot', allow: '/', disallow: DISALLOW_PATHS },
      { userAgent: 'Google-Extended', allow: '/', disallow: DISALLOW_PATHS },
      { userAgent: 'Applebot-Extended', allow: '/', disallow: DISALLOW_PATHS },
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
    host: BASE_URL,
  };
}
