/**
 * robots.txt — generated by Next.js Metadata API.
 *
 * Policy (per SEO master plan 2026-05-20):
 * - Allow standard crawlers everywhere except private routes
 * - Allow every AI crawler and assistant fetcher (list below; Raul 06.10.2026:
 *   „deblochează toți AI”) — visibility in ChatGPT search, Copilot, Perplexity,
 *   Gemini, Claude. Assistant fetchers may also open the first order step.
 * - Block:
 *   - /admin/   (admin panel, not for indexing)
 *   - /api/     (API routes, no human-readable content)
 *   - /comanda/ (order wizard — user-state, not public content)
 *   - /auth/    (login/register flows)
 *   - /account/ (customer account area)
 */

import type { MetadataRoute } from 'next';
import { BASE_URL } from '@/lib/seo/constants';
import { AI_ASSISTANT_FETCHERS, AI_CRAWLERS } from '@/lib/seo/ai-bots';

const DISALLOW_PATHS = [
  '/admin/',
  '/api/',
  '/comanda/',
  '/auth/',
  '/account/',
  '/orders/',
];

/**
 * Assistant fetchers (ChatGPT-User, Claude-User, Perplexity-User) act for a
 * person who asked them to open a page, so they may open the first step of
 * the order form (`/comanda/<serviciu>/`, still noindex through the order
 * layout). Checkout, status and success pages carry order ids and stay closed.
 */
const ASSISTANT_DISALLOW_PATHS = [
  '/admin/',
  '/api/',
  '/comanda/checkout/',
  '/comanda/success/',
  '/comanda/status/',
  '/auth/',
  '/account/',
  '/orders/',
];


export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // Default policy for all crawlers
      { userAgent: '*', allow: '/', disallow: DISALLOW_PATHS },
      // Explicitly allow AI crawlers (some default to denied without an entry)
      ...AI_CRAWLERS.map((userAgent) => ({ userAgent, allow: '/', disallow: DISALLOW_PATHS })),
      // Assistant fetchers may open the first step of the order form
      ...AI_ASSISTANT_FETCHERS.map((userAgent) => ({ userAgent, allow: '/', disallow: ASSISTANT_DISALLOW_PATHS })),
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
    // `host` era emis ca `Host: https://eghiseul.ro` — sintaxă greșită pentru o
    // directivă oricum depreciată (era Yandex-only și cerea doar domeniul, fără
    // schemă). Google o ignoră; o scoatem ca să nu rămână balast într-un fișier
    // pe care îl citesc și crawlerele AI. Audit 28.07.2026.
  };
}
