/**
 * Countries that are members of the Hague Apostille Convention
 * and commonly requested by Romanian citizens living abroad.
 *
 * Country names are in Romanian, sorted alphabetically.
 * Source: Hague Conference on Private International Law (HCCH)
 * https://www.hcch.net/en/instruments/conventions/status-table/?cid=41
 *
 * Ported from cazierjudiciaronline.com / config / apostila-countries.ts
 */
export const APOSTILA_COUNTRIES = [
  'Africa de Sud',
  'Albania',
  'Andorra',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Belarus',
  'Belgia',
  'Bolivia',
  'Bosnia și Herțegovina',
  'Brazilia',
  'Bulgaria',
  'Canada',
  'Chile',
  'China (Hong Kong)',
  'China (Macao)',
  'Cipru',
  'Columbia',
  'Coreea de Sud',
  'Costa Rica',
  'Croația',
  'Danemarca',
  'Ecuador',
  'Elveția',
  'Emiratele Arabe Unite',
  'Estonia',
  'Filipine',
  'Finlanda',
  'Franța',
  'Georgia',
  'Germania',
  'Grecia',
  'India',
  'Irlanda',
  'Islanda',
  'Israel',
  'Italia',
  'Japonia',
  'Kazahstan',
  'Letonia',
  'Liechtenstein',
  'Lituania',
  'Luxemburg',
  'Macedonia de Nord',
  'Malta',
  'Marea Britanie',
  'Mexic',
  'Moldova',
  'Monaco',
  'Muntenegru',
  'Norvegia',
  'Noua Zeelandă',
  'Olanda',
  'Oman',
  'Panama',
  'Paraguay',
  'Peru',
  'Polonia',
  'Portugalia',
  'Qatar',
  'Republica Cehă',
  'România',
  'Rusia',
  'San Marino',
  'Serbia',
  'Singapore',
  'Slovacia',
  'Slovenia',
  'Spania',
  'Statele Unite ale Americii',
  'Suedia',
  'Turcia',
  'Ucraina',
  'Ungaria',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
] as const;

export type ApostilaCountry = (typeof APOSTILA_COUNTRIES)[number];
