/**
 * Complete list of world countries in Romanian.
 * Used for "Tara Nasterii" dropdown in the form.
 * Sorted alphabetically.
 */
export const COUNTRIES: string[] = [
  "Afganistan",
  "Africa de Sud",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua și Barbuda",
  "Arabia Saudită",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgia",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia și Herțegovina",
  "Botswana",
  "Brazilia",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodgia",
  "Camerun",
  "Canada",
  "Capul Verde",
  "Cehia",
  "Republica Centrafricană",
  "Chile",
  "China",
  "Cipru",
  "Colombia",
  "Comore",
  "Congo",
  "Republica Democrată Congo",
  "Coreea de Nord",
  "Coreea de Sud",
  "Costa Rica",
  "Coasta de Fildeș",
  "Croația",
  "Cuba",
  "Danemarca",
  "Djibouti",
  "Dominica",
  "Ecuador",
  "Egipt",
  "El Salvador",
  "Elveția",
  "Emiratele Arabe Unite",
  "Eritreea",
  "Estonia",
  "Eswatini",
  "Etiopia",
  "Fiji",
  "Filipine",
  "Finlanda",
  "Franța",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germania",
  "Ghana",
  "Grecia",
  "Grenada",
  "Guatemala",
  "Guineea",
  "Guineea Ecuatorială",
  "Guineea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "India",
  "Indonezia",
  "Iordania",
  "Irak",
  "Iran",
  "Irlanda",
  "Islanda",
  "Israel",
  "Italia",
  "Jamaica",
  "Japonia",
  "Kazahstan",
  "Kenya",
  "Kârgâzstan",
  "Kiribati",
  "Kosovo",
  "Kuweit",
  "Laos",
  "Lesotho",
  "Letonia",
  "Liban",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburg",
  "Macedonia de Nord",
  "Madagascar",
  "Malaezia",
  "Malawi",
  "Maldive",
  "Mali",
  "Malta",
  "Marea Britanie",
  "Maroc",
  "Insulele Marshall",
  "Mauritania",
  "Mauritius",
  "Mexic",
  "Micronezia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Muntenegru",
  "Mozambic",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norvegia",
  "Noua Zeelandă",
  "Țările de Jos",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Noua Guinee",
  "Paraguay",
  "Peru",
  "Polonia",
  "Portugalia",
  "Qatar",
  "Republica Dominicană",
  "România",
  "Rusia",
  "Rwanda",
  "Saint Kitts și Nevis",
  "Saint Lucia",
  "Saint Vincent și Grenadine",
  "Samoa",
  "San Marino",
  "São Tomé și Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Siria",
  "Slovacia",
  "Slovenia",
  "Insulele Solomon",
  "Somalia",
  "Spania",
  "Sri Lanka",
  "Statele Unite ale Americii",
  "Sudan",
  "Sudanul de Sud",
  "Suedia",
  "Surinam",
  "Tadjikistan",
  "Tailanda",
  "Taiwan",
  "Tanzania",
  "Timorul de Est",
  "Togo",
  "Tonga",
  "Trinidad și Tobago",
  "Tunisia",
  "Turcia",
  "Turkmenistan",
  "Tuvalu",
  "Ucraina",
  "Uganda",
  "Ungaria",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

/**
 * EU member states (27 countries, post-Brexit) — Romanian names.
 * Used to filter the "Țara Nașterii" dropdown when the user picks
 * "Născut în Uniunea Europeană" at step 1.
 */
export const EU_COUNTRIES: readonly string[] = [
  'Austria',
  'Belgia',
  'Bulgaria',
  'Cehia',
  'Cipru',
  'Croația',
  'Danemarca',
  'Estonia',
  'Finlanda',
  'Franța',
  'Germania',
  'Grecia',
  'Irlanda',
  'Italia',
  'Letonia',
  'Lituania',
  'Luxemburg',
  'Malta',
  'Polonia',
  'Portugalia',
  'România',
  'Slovacia',
  'Slovenia',
  'Spania',
  'Suedia',
  'Țările de Jos',
  'Ungaria',
];

const EU_SET = new Set(EU_COUNTRIES);

/** Countries outside the EU (everything in COUNTRIES that's NOT in EU_COUNTRIES). */
export const NON_EU_COUNTRIES: readonly string[] = COUNTRIES.filter(
  (c) => !EU_SET.has(c)
);

/**
 * Get the appropriate country list based on the user's foreign-type pick.
 *  - 'eu'      → EU member states only (27)
 *  - 'non-eu'  → all non-EU countries
 *  - undefined → full world list (fallback / Romanian flow)
 */
export function getCountriesForForeignType(
  foreignType: 'eu' | 'non-eu' | undefined
): readonly string[] {
  if (foreignType === 'eu') return EU_COUNTRIES;
  if (foreignType === 'non-eu') return NON_EU_COUNTRIES;
  return COUNTRIES;
}
