import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { z } from 'zod'
import { calculateEstimatedCompletion } from '@/lib/delivery-calculator'
import { STATUS_OPTIONS } from '@/lib/admin/status-options'

// Validation schema for creating an order
const createOrderSchema = z.object({
  serviceId: z.string().uuid(),
  selectedOptions: z.array(z.object({
    optionId: z.string().uuid(),
    value: z.string()
  })).optional(),
  customerData: z.object({
    fullName: z.string().min(2),
    cnp: z.string().regex(/^[1-9]\d{12}$/, 'CNP invalid').optional(),
    email: z.string().email(),
    phone: z.string().min(10),
    address: z.object({
      street: z.string().min(3),
      city: z.string().min(2),
      county: z.string().min(2),
      postalCode: z.string().min(5)
    }).optional()
  }),
  deliveryMethod: z.enum(['email', 'registered_mail', 'courier']).optional(),
  additionalNotes: z.string().max(1000).optional()
})

// POST /api/orders - Create a new order
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    // Check authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: 'UNAUTHORIZED',
            message: 'Authentication required'
          }
        },
        { status: 401 }
      )
    }

    // Parse and validate request body
    const body = await request.json()
    const validation = createOrderSchema.safeParse(body)

    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Invalid order data',
            details: validation.error.flatten().fieldErrors
          }
        },
        { status: 400 }
      )
    }

    const { serviceId, selectedOptions, customerData, deliveryMethod, additionalNotes } = validation.data

    // Fetch service to verify it exists and is active
    const { data: service, error: serviceError } = await supabase
      .from('services')
      .select('*')
      .eq('id', serviceId)
      .eq('is_active', true)
      .single()

    if (serviceError || !service) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: 'SERVICE_NOT_FOUND',
            message: 'Service not found or inactive'
          }
        },
        { status: 404 }
      )
    }

    // Calculate total price
    let totalPrice = parseFloat(String(service.base_price))
    const processedOptions: Array<{ optionId: string; name: string; value: string; price: number }> = []

    if (selectedOptions && selectedOptions.length > 0) {
      // Fetch selected options
      const optionIds = selectedOptions.map(o => o.optionId)
      const { data: options } = await supabase
        .from('service_options')
        .select('*')
        .in('id', optionIds)
        .eq('service_id', serviceId)

      if (options) {
        for (const selectedOpt of selectedOptions) {
          const option = options.find(o => o.id === selectedOpt.optionId)
          if (option) {
            const optionPrice = parseFloat(String(option.price))
            totalPrice += optionPrice
            processedOptions.push({
              optionId: option.id,
              name: option.name,
              value: selectedOpt.value,
              price: optionPrice
            })
          }
        }
      }
    }

    // Create the order
    // Note: order_number is generated by database trigger but TypeScript requires it
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        order_number: 'TEMP', // Will be overwritten by generate_order_number() trigger
        user_id: user.id,
        service_id: serviceId,
        status: 'pending',
        customer_data: customerData,
        selected_options: processedOptions,
        delivery_method: deliveryMethod,
        delivery_address: customerData.address || null,
        base_price: parseFloat(String(service.base_price)),
        options_price: totalPrice - parseFloat(String(service.base_price)),
        total_price: totalPrice,
        payment_status: 'unpaid'
      })
      .select()
      .single()

    if (orderError) {
      console.error('Order creation error:', orderError)
      return NextResponse.json(
        {
          success: false,
          error: {
            code: 'DATABASE_ERROR',
            message: 'Failed to create order'
          }
        },
        { status: 500 }
      )
    }

    // Format order number
    const orderNumber = `ORD-${new Date().getFullYear()}-${String(order.order_number).padStart(7, '0')}`

    return NextResponse.json(
      {
        success: true,
        data: {
          order: {
            id: order.id,
            orderNumber,
            userId: order.user_id,
            serviceId: order.service_id,
            serviceName: service.name,
            status: order.status,
            totalAmount: totalPrice,
            currency: 'RON',
            breakdown: {
              basePrice: parseFloat(String(service.base_price)),
              optionsTotal: totalPrice - parseFloat(String(service.base_price)),
              subtotal: totalPrice,
              tax: 0,
              total: totalPrice
            },
            selectedOptions: processedOptions,
            customerData: order.customer_data,
            deliveryMethod: order.delivery_method,
            additionalNotes,
            paymentStatus: order.payment_status,
            paymentIntentId: order.stripe_payment_intent_id,
            createdAt: order.created_at,
            updatedAt: order.updated_at,
            estimatedCompletion: new Date(
              Date.now() + (service.estimated_days || 5) * 24 * 60 * 60 * 1000
            ).toISOString()
          }
        }
      },
      { status: 201 }
    )
  } catch (error) {
    console.error('Unexpected error:', error)
    return NextResponse.json(
      {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred'
        }
      },
      { status: 500 }
    )
  }
}

// GET /api/orders - List user orders
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient()

    // Check authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: 'UNAUTHORIZED',
            message: 'Authentication required'
          }
        },
        { status: 401 }
      )
    }

    const { searchParams } = new URL(request.url)
    const statusParam = searchParams.get('status')
    const limit = Math.min(parseInt(searchParams.get('limit') || '20'), 50)
    const offset = parseInt(searchParams.get('offset') || '0')

    // A `?status=` we do not recognise is dropped, and the whole list comes back
    // unfiltered — which looks like the filter worked and returned everything.
    // The list of what exists is the operator's own, so `standby`, `paid`,
    // `shipped` and the rest stop being silently ignored here.
    const knownStatuses = new Set(STATUS_OPTIONS.map(option => option.value))
    const status = statusParam && knownStatuses.has(statusParam) ? statusParam : null

    // Build query
    let query = supabase
      .from('orders')
      .select(`
        *,
        services (
          id,
          slug,
          name,
          category,
          estimated_days,
          urgent_days
        )
      `, { count: 'exact' })
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1)

    if (status) {
      query = query.eq('status', status)
    }

    const { data: orders, error, count } = await query

    if (error) {
      console.error('Orders fetch error:', error)
      return NextResponse.json(
        {
          success: false,
          error: {
            code: 'DATABASE_ERROR',
            message: 'Failed to fetch orders'
          }
        },
        { status: 500 }
      )
    }

    // The completion date for an order that has none stored, computed exactly
    // as `api/orders/[id]` computes it: the service term (halved, or
    // `urgent_days`, when the customer bought urgency) plus a two-day buffer,
    // through the calculator that knows about weekends, holidays and the daily
    // cutoff.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const fallbackEstimate = (order: any): string | null => {
      const baseDays = order.services?.estimated_days
      if (!baseDays) return null
      const hasUrgent = ((order.selected_options as Array<{ option_name?: string; optionName?: string }>) || [])
        .some(opt => (opt.optionName || opt.option_name || '').toLowerCase().includes('urgent'))
      const processingDays = hasUrgent
        ? (order.services?.urgent_days || Math.max(2, Math.ceil(baseDays / 2)))
        : baseDays
      const { maxDate } = calculateEstimatedCompletion({
        baseDays: processingDays + 2,
        includeCourierLeg: false,
        orderDate: order.created_at ? new Date(order.created_at) : new Date(),
      })
      return maxDate ? `${maxDate}T16:00:00Z` : null
    }

    // How many documents this customer can already download, per order. One
    // query for the whole page rather than one per card, and only the rows
    // marked visible to the client — 646 of the 1468 documents are internal.
    const orderIds = (orders ?? []).map(o => o.id)
    const documentCounts = new Map<string, number>()
    if (orderIds.length > 0) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data: docs } = await (supabase as any)
        .from('order_documents')
        .select('order_id')
        .in('order_id', orderIds)
        .eq('visible_to_client', true)
      for (const doc of docs ?? []) {
        documentCounts.set(doc.order_id, (documentCounts.get(doc.order_id) ?? 0) + 1)
      }
    }

    // Transform orders
    const transformedOrders = orders?.map(order => {
      const createdDate = order.created_at ? new Date(order.created_at) : new Date()
      // Use friendly_order_id if available, otherwise generate from order_number
      const orderNumber = order.friendly_order_id ||
        `ORD-${createdDate.getFullYear()}-${String(order.order_number).padStart(7, '0')}`
      return {
        id: order.id,
        orderNumber,
        friendly_order_id: order.friendly_order_id,
        service: order.services ? {
          id: order.services.id,
          slug: order.services.slug,
          name: order.services.name,
          category: order.services.category
        } : null,
        status: order.status,
        totalAmount: parseFloat(String(order.total_price)),
        total_price: parseFloat(String(order.total_price)),
        currency: 'RON',
        paymentStatus: order.payment_status,
        createdAt: order.created_at,
        created_at: order.created_at,
        updatedAt: order.updated_at,
        // What the account needs to answer "where is it, do I have to do
        // something, where are my documents" without a second round-trip.
        paidAt: order.paid_at,
        // The SAME date the order's own page shows. The card used to be able to
        // compute its own from `estimated_days`, which would have given the
        // customer two different promises for one order — the persisted date
        // when it exists (234 of 439 paid orders in 120 days), otherwise the
        // same holiday- and cutoff-aware calculation the detail route runs.
        estimatedCompletionDate: order.estimated_completion_date ?? fallbackEstimate(order),
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        estimatedDays: (order.services as any)?.estimated_days ?? null,
        tracking: order.delivery_tracking_number
          ? {
              number: order.delivery_tracking_number,
              url: order.delivery_tracking_url ?? null,
              status: order.delivery_tracking_status ?? null,
            }
          : null,
        documentsAvailable: documentCounts.get(order.id) ?? 0,
        invoiceIssued: !!order.invoice_issued_at,
        // The invoice PDF, so the card can hand it over directly instead of
        // sending the customer one page deeper for a file we already have.
        invoiceUrl: order.invoice_url ?? null,
        // When the order was finished, which is what the document's validity is
        // counted from (`src/lib/lifecycle/rules.ts`). The account is the only
        // place that can say "your cazier expires on the 3rd of March" while the
        // customer is looking at the order it came from.
        // `completed_at` exists in the database (trigger from migration 159);
        // the generated types are stale.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        completedAt: (order as any).completed_at ?? null,
      }
    }) || []

    return NextResponse.json({
      success: true,
      data: {
        orders: transformedOrders,
        pagination: {
          total: count || 0,
          limit,
          offset,
          hasMore: (offset + limit) < (count || 0)
        }
      }
    })
  } catch (error) {
    console.error('Unexpected error:', error)
    return NextResponse.json(
      {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred'
        }
      },
      { status: 500 }
    )
  }
}
