-- Migration 041: Abandoned cart system + sandbox filter + recovery coupons
-- Date: 2026-05-27
--
-- Brings the eghiseul.ro admin closer to parity with cazierjudiciaronline.com:
--   1. `abandoned` allowed in orders.status (currently rejected by the check)
--   2. `is_test` boolean for sandbox/test filtering (Stripe test-mode orders)
--   3. `system_kind` on coupons for marking recovery-cron rows distinctly
--   4. Index on (status, created_at) for fast pending-sweep
--
-- See docs/admin/abandoned-carts.md for the operational handbook.

BEGIN;

-- ─── 1. Allow `abandoned` status ──────────────────────────────────────────────

ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders ADD CONSTRAINT orders_status_check
  CHECK (status IN (
    'draft',
    'pending',
    'abandoned',                 -- NEW (2026-05-27): auto-flipped from pending
    'paid',
    'processing',
    'documents_generated',
    'submitted_to_institution',
    'document_received',
    'extras_in_progress',
    'kyc_pending',
    'kyc_approved',
    'kyc_rejected',
    'in_progress',
    'document_ready',
    'shipped',
    'delivered',
    'completed',
    'cancelled',
    'refunded'
  ));

-- ─── 2. is_test column (sandbox filter) ───────────────────────────────────────

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS is_test BOOLEAN NOT NULL DEFAULT FALSE;

-- Fast filter on the admin list — most queries restrict to is_test=false.
CREATE INDEX IF NOT EXISTS idx_orders_is_test_status
  ON orders (is_test, status, created_at DESC);

COMMENT ON COLUMN orders.is_test IS
  'TRUE when the order was created against a Stripe test key (sk_test_*). Admin list hides these by default; chip "Doar test" surfaces them. See is_test detection in create-payment-intent route.';

-- ─── 3. order_history event_type for system actions ───────────────────────────

-- Ensure 'abandoned' is allowed as an event_type so the auto-abandon cron can
-- insert an audit row (the constraint was set in migration 035 with the
-- statuses it knew about then).

DO $$
BEGIN
  -- Idempotent: only modify when the constraint exists with the original set.
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'order_history_event_type_check'
  ) THEN
    ALTER TABLE order_history DROP CONSTRAINT order_history_event_type_check;
  END IF;
END $$;

ALTER TABLE order_history ADD CONSTRAINT order_history_event_type_check
  CHECK (event_type IN (
    -- Legacy values found in production rows (don't drop them).
    'status_changed',
    'order_submitted',
    'payment_confirmed',
    'document_generated',
    -- Future-friendly additions.
    'payment_received',
    'document_uploaded',
    'note_added',
    'admin_action',
    'kyc_verified',
    'kyc_rejected',
    'awb_created',
    'shipped',
    'delivered',
    'abandoned',                 -- NEW (2026-05-27): auto-abandon cron
    'recovery_email_sent',       -- NEW (2026-05-27): recovery cron
    'cancelled',
    'refunded'
  ));

-- ─── 4. Coupons: system_kind for recovery rows ────────────────────────────────

ALTER TABLE coupons
  ADD COLUMN IF NOT EXISTS system_kind TEXT
  CHECK (system_kind IS NULL OR system_kind IN ('recovery'));

COMMENT ON COLUMN coupons.system_kind IS
  'NULL for admin-created coupons. ''recovery'' for rows auto-generated by the recovery-email cron — admin UI uses this to separate the Recovery tab from Manual. Each recovery coupon is single-use, 48h validity.';

-- Index makes the Recovery tab in /admin/coupons cheap to render.
CREATE INDEX IF NOT EXISTS idx_coupons_system_kind
  ON coupons (system_kind, created_at DESC)
  WHERE system_kind IS NOT NULL;

-- ─── 5. Orders: recovery email column ─────────────────────────────────────────

-- Track whether the recovery email cron has already mailed a given order so
-- the loop doesn't re-spam the customer.
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS recovery_email_sent_at TIMESTAMPTZ;

COMMENT ON COLUMN orders.recovery_email_sent_at IS
  'When the recovery cron sent the customer a re-engagement email with an auto-generated coupon. NULL = never sent. Set by /api/cron/recovery-emails (runs every 15 min via vercel.json).';

COMMIT;

-- Verify (visible in psql / Supabase logs)
SELECT
  conname,
  pg_get_constraintdef(oid) AS def
FROM pg_constraint
WHERE conname IN ('orders_status_check', 'order_history_event_type_check');
